version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recalde-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-119fg0kk82b9k"
s3_prefix = "recalde-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
